/* auto-generated by NAPI-RS */
/* eslint-disable */

export interface TerminalConfig {
  scrollbackLines?: number
  enableImages?: boolean
  enableHyperlinks?: boolean
  bracketedPaste?: boolean
}

export interface CellAttributes {
  bold: boolean
  italic: boolean
  underline: boolean
  strikethrough: boolean
  reverse: boolean
  dim: boolean
  hidden: boolean
  blink: boolean
}

export interface Cell {
  text: string
  fgColor: number
  bgColor: number
  attrs: CellAttributes
}

export interface CursorPosition {
  col: number
  row: number
}

/**
 * Terminal emulator instance
 */
export class Terminal {
  /**
   * Create a new terminal
   * @param cols - Number of columns
   * @param rows - Number of rows
   * @param config - Optional terminal configuration
   */
  constructor(cols: number, rows: number, config?: TerminalConfig)

  /**
   * Write data to the terminal
   * @param data - Data to write (Buffer or Uint8Array)
   */
  write(data: Buffer | Uint8Array): void

  /**
   * Get the current cursor position
   */
  cursorPosition(): CursorPosition

  /**
   * Get the terminal size
   */
  size(): CursorPosition

  /**
   * Resize the terminal
   * @param cols - New number of columns
   * @param rows - New number of rows
   */
  resize(cols: number, rows: number): void

  /**
   * Get a cell at the specified position
   * @param col - Column position
   * @param row - Row position
   * @returns Cell data or null if position is invalid
   */
  getCell(col: number, row: number): Cell | null

  /**
   * Get text from a line
   * @param row - Row number
   * @returns Line text or null if row is invalid
   */
  getLineText(row: number): string | null

  /**
   * Get all visible text
   * @returns All visible lines joined with newlines
   */
  getVisibleText(): string

  /**
   * Clear the selection
   */
  clearSelection(): void

  /**
   * Clear all markers
   */
  clearMarkers(): void

  /**
   * Check if a line is dirty (changed since last clear)
   * @param row - Row number
   */
  isLineDirty(row: number): boolean

  /**
   * Clear dirty line tracking
   */
  clearDirty(): void
}

/**
 * Get library version
 */
export function version(): string

/**
 * Create a terminal with default configuration
 * @param cols - Number of columns
 * @param rows - Number of rows
 */
export function createTerminal(cols: number, rows: number): Terminal
